---
title: "Cox regression"
author: "Byhamre"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    citation_package: natbib
    keep_tex: yes
    number_sections: yes
    toc: no
    toc_depth: 2
  bookdown::html_document2:
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
  bookdown::word_document2:
    toc: no
    toc_depth: 2
citation_package: natbib
##classoption: titlepage
bibliography: snus2.bib
titlepage: no
biblio-style: apalike
documentclass: article
fontsize: 11pt
header-includes:
- \usepackage[utf8]{inputenc}
- \usepackage{graphicx}
- \usepackage{sectsty}
- \subsectionfont{\normalfont\itshape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", fig.path = "figs/", cache = FALSE)
library(eha)
source("R/fit.out.R")
source("R/tbl.R")
source("R/unicode.R")
options(show.signif.stars = FALSE)
```

# Read data

```{r}
vip <- readRDS("Rdata/vip.rds")

```

# Nya coxregressioner

## All-cause mortality
### Crude model
```{r crudeall, results='asis'}
library(eha)
source("R/ltxCoef3.R")
fit <- coxreg(Surv(exit, event) ~ snususe, data = vip)
dr <- drop1(fit, test = "Chisq")
ltxCoef3(fit, digits = 4, dr = dr, caption = "All-cause mortality, crude model")
```

### Basic model
```{r basicall, results='asis'}
library(eha)
source("R/ltxCoef3.R")
fit <- coxreg(Surv(exit, event) ~ sex + age +
                   us.ar + snususe, data = vip)
dr <- drop1(fit, test = "Chisq")
ltxCoef3(fit, digits = 4, dr = dr, caption = "All-cause mortality, basic model")
```

### Multivariable model
```{r multiall, results='asis'}
library(eha)
source("R/ltxCoef3.R")
vip0 <- na.omit(vip[, c("exit", "event", "age", "snususe", "sex", "us.ar", "livingalone", "education", "Boende", "income.90", "phyact")])
fit <- coxreg(Surv(exit, event) ~ snususe + age + sex + us.ar + livingalone + education + 
                Boende + income.90 + phyact,  data = vip0)
dr = drop1(fit, test = "Chisq")
ltxCoef3(fit, digits = 4, dr = dr, 
         caption = "All-cause mortality, multivariable model")
```

### Mediator model
```{r mediatorall, results='asis'}
library(eha)
source("R/ltxCoef3.R")
vip0 <- (vip[, c("exit", "event", "snususe", "age", "sex", "us.ar", "livingalone", "education", "Boende", "income.90", "phyact", "dependent", "diabetes", "bmi", "alder.VIP")])
vip0$dependent[is.na(vip0$dependent)] <- FALSE
vip0$diabetes[is.na(vip0$diabetes)] <- "No"
vip0 <- na.omit(vip0)
fit <- coxreg(Surv(exit, event) ~ snususe + sex + us.ar + livingalone + education + factor(alder.VIP) +
                Boende + income.90 + phyact + dependent + diabetes + bmi,  data = vip0)
dr = drop1(fit, test = "Chisq")
ltxCoef3(fit, digits = 4, dr = dr, 
         caption = "All-cause mortality, mediator model")
```

